### ISSUE TITLE
ES attempts to find the system 'nes' even if the systems config file is empty

### ISSUE THREAD

**Issue by shagia** [MisterTea/EmulationStation#1]
Not sure if this is a user issue or just a issue with the software, but it seems that ES keeps trying to find a directory pointing to "~/roms/nes" instead of any other directory listed. Assuming it's coming from the es_systems.cfg file, I've tried editing the file and I've actually found nothing pointing at that directory. Even removing the 'nes' system tag from the cfg file brings up the same error, so I'm a bit confused.

I've done a couple of clean installs only to get the same error even when following the instructions, thinking I might have been misreading something, but even then, same issue.

![Debug terminal](https://0x0.st/XfF.png)

**Comment by MisterTea** [comment]
Can you post a copy of your `.emulationstation/es_systems.cfg` file?

**Comment by shagia** [comment]
[Yes, I can!](https://0x0.st/XJG.cfg) 

I've tried pushing it to different directories, also got kinda confused on what's the correct 'slash' to be using which is why I started wondering if it's just my illiteracy possibly causing this, but even with the default es_systems.cfg file that comes with [2.0.2](https://github.com/MisterTea/EmulationStation/releases/tag/v2.0.2), I continue to get the same error. It doesn't even seem to look in the other 'system' paths assigned.

**Comment by MisterTea** [comment]
You must have another es_systems.cfg file somewhere on your hard drive.
Are you using the bat file to run ESMAME?  The bat file sets your home
directory correctly so that it will find the .emulationstation folder
inside ESMAME and not create a new one in your personal home directory.

**Comment by shagia** [comment]
So I looked at my mistakes, and yeah, I had another es_systems.cfg file in my home directory on my C: drive. Deleted the last traces of ES, but the problem continued. One thing I didn't mention though, is that I'm running ES with elevated privileges, because not doing so just doesn't launch it for some reason, not even the version that comes with ESMAME launches. I turned off privilege elevation maybe assuming that ES is just looking in the wrong directory, but now ES just doesn't launch. It leaves an unfinished log in the folder though, it wasn't doing that with elevated privileges.

> lvl2:     EmulationStation - v2.0.1a, built Nov 24 2015 - 16:29:05
> lvl2:     Setting local directory to J:\Games\ESMAME/locale/lang
> lvl2:     Locals set...
> lvl2:     Creating surface...

This might not be your problem since this was happening with ES by itself.

**Comment by MisterTea** [comment]
After you ran it again, did it make a new es_systems.cfg file?

**Comment by shagia** [comment]
Sadly, it didn't. It only seems to just write new logs.

**Comment by MisterTea** [comment]
The new log ends at "creating surface"? What happens after that, crash?

**Comment by shagia** [comment]
Yeah, it just crashes. When running the `launch.bat` file, [all I really get is just this, and nothing else. The terminal dismisses it's self afterwards.](https://0x0.st/Xy6.png)

[Using the debug command does the same thing but Windows catches it.](https://0x0.st/Xyl.png)

**Comment by MisterTea** [comment]
Yeah if you are dying on creating surface, it means that your graphics card
doesn't support a high enough version of OpenGL. You need a more modern
graphics card :-(

**Comment by shagia** [comment]
Ohhhhh, that's a bit gutting. No worries, thank you for helping out with my issue!
